### ISSUE TITLE
https url issue

### ISSUE THREAD

**Issue by jaydenlin** [HanVincent/ResultHider#1]
The app will have a little issue when I put url with http.

**Comment by wbhan95** [comment]
This happened because the extension only matches the domain part only. Therefore, full url is incomparable to domain part.
I fixed it by validating user's input (is legal href format or not) in order to get correct domain name.

https://github.com/HanVincent/ResultHider/commit/8e3a2737abe6e7de8b678b27b022ba86996a49f1

**Comment by jaydenlin** [comment]
Awesome ! I love this extension, it's really helpful.
